# Generated by Django 2.2.5 on 2019-09-22 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Мобильный телефон')),
                ('firm_name', models.CharField(blank=True, max_length=100, verbose_name='Название фирмы')),
                ('legal_adress', models.CharField(blank=True, max_length=100, verbose_name='Юридический адрес')),
                ('INN', models.IntegerField(blank=True, null=True, verbose_name='ИНН')),
                ('KPP', models.IntegerField(blank=True, null=True, verbose_name='КПП')),
                ('requisites_file', models.FileField(blank=True, upload_to='', verbose_name='Файл с реквизитами')),
                ('slug', models.SlugField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Nickname')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
