# Generated by Django 2.2.5 on 2019-10-05 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191002_1324'),
        ('personal_cabinet', '0002_auto_20190929_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal_cabinet.Client')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Research')),
            ],
        ),
    ]
