# Generated by Django 2.2.5 on 2019-09-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0002_auto_20190922_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='requisites_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл с реквизитами'),
        ),
    ]
