# Generated by Django 2.2.5 on 2019-10-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191002_1324'),
        ('personal_cabinet', '0003_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='research',
        ),
        migrations.AddField(
            model_name='favorite',
            name='research',
            field=models.ManyToManyField(to='products.Research'),
        ),
    ]
