# Generated by Django 2.2.5 on 2019-10-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0005_auto_20191005_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='research',
            field=models.ManyToManyField(blank=True, to='products.Research'),
        ),
    ]
