# Generated by Django 2.2.5 on 2019-11-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SplitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('napr', models.CharField(blank=True, max_length=2, null=True)),
                ('period', models.CharField(blank=True, max_length=7, null=True)),
                ('strana', models.CharField(blank=True, max_length=3, null=True)),
                ('tnved', models.CharField(blank=True, max_length=10, null=True)),
                ('edizm', models.CharField(blank=True, max_length=20, null=True)),
                ('stoim', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('netto', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('kol', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('region_s', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'split_data',
                'managed': False,
            },
        ),
    ]
