# Generated by Django 2.2.5 on 2019-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20191126_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticdata',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
