# Generated by Django 2.2.5 on 2019-11-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_auto_20191127_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticdata',
            name='datetime',
        ),
    ]
