# Generated by Django 2.2.5 on 2019-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_statisticdata_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticdata',
            name='datetime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
