# Generated by Django 2.2.5 on 2019-11-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0007_auto_20191127_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticdata',
            name='datetime',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
