# Generated by Django 2.2.5 on 2019-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0008_auto_20191127_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticdata',
            name='period',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
