# Generated by Django 2.2.5 on 2019-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0009_auto_20191127_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticdata',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
