# Generated by Django 2.2.5 on 2019-12-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0014_auto_20191209_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticdata',
            name='tnved2',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
