# Generated by Django 2.2.5 on 2019-12-16 07:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0015_statisticdata_tnved2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticdata',
            name='tnved2',
        ),
        migrations.AddField(
            model_name='statisticdata',
            name='split_tnved',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True),
        ),
    ]
