# Generated by Django 2.2.5 on 2019-12-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0017_tnvedhandbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnvedhandbook',
            name='tnved',
            field=models.BigIntegerField(),
        ),
    ]
