# Generated by Django 2.2.5 on 2019-12-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0018_auto_20191219_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnvedhandbook',
            name='tnved',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
