# Generated by Django 2.2.5 on 2019-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0019_auto_20191219_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticdata',
            name='tnved_eight',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='statisticdata',
            name='tnved_four',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='statisticdata',
            name='tnved_six',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='statisticdata',
            name='tnved_two',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
