# Generated by Django 2.2.5 on 2019-12-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0020_auto_20191220_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticdata',
            name='tnved_ten',
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='tnved_eight',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='tnved_four',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='tnved_six',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
    ]
