# Generated by Django 2.2.5 on 2019-12-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0022_auto_20191223_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAggregateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('imp_sum_cost', models.BigIntegerField(verbose_name='Импорт - суммарная стоимость')),
                ('exp_sum_cost', models.BigIntegerField(verbose_name='Экспорт - суммарная стоимость')),
                ('imp_sum_weight', models.BigIntegerField(verbose_name='Импорт - суммарный вес')),
                ('exp_sum_weight', models.BigIntegerField(verbose_name='Экспорт - суммарный вес')),
            ],
        ),
        migrations.DeleteModel(
            name='TnvedAggregateData',
        ),
    ]
