# Generated by Django 2.2.5 on 2019-12-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0023_auto_20191225_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryaggregatedata',
            name='exp_sum_cost',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Экспорт - суммарная стоимость'),
        ),
        migrations.AlterField(
            model_name='countryaggregatedata',
            name='exp_sum_weight',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Экспорт - суммарный вес'),
        ),
        migrations.AlterField(
            model_name='countryaggregatedata',
            name='imp_sum_cost',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Импорт - суммарная стоимость'),
        ),
        migrations.AlterField(
            model_name='countryaggregatedata',
            name='imp_sum_weight',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Импорт - суммарный вес'),
        ),
    ]
