# Generated by Django 2.2.5 on 2019-12-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0024_auto_20191225_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryaggregatedata',
            name='period',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
