# Generated by Django 2.2.5 on 2020-01-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0026_countryhandbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticdata',
            name='split_tnved',
        ),
        migrations.AddField(
            model_name='countryaggregatedata',
            name='country_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
