# Generated by Django 2.2.8 on 2020-01-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0026_countryhandbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryaggregatedata',
            name='country_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
