# Generated by Django 2.2.8 on 2020-01-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0027_countryaggregatedata_country_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticdata',
            name='split_tnved',
        ),
    ]
