# Generated by Django 2.2.5 on 2020-01-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0027_auto_20200103_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticdata',
            name='kol',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=22, null=True),
        ),
    ]
