# Generated by Django 2.2.5 on 2020-01-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0028_auto_20200104_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticdata',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
