# Generated by Django 2.2.5 on 2019-09-22 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('personal_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_frequency', models.CharField(choices=[('MU', 'Ежемесячное обновление'), ('QU', 'Ежеквартальное обновление')], max_length=2, verbose_name='частота обновления')),
                ('duration', models.CharField(choices=[('OM', 'На один месяц'), ('OQ', 'На один квартал'), ('HY', 'На пол года'), ('OY', 'На один год')], max_length=2, verbose_name='подписка')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_cabinet.Client', verbose_name='Клиент')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Research', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
