# Generated by Django 2.2.5 on 2019-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190929_1739'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='research',
        ),
        migrations.AddField(
            model_name='cart',
            name='research',
            field=models.ManyToManyField(blank=True, to='products.Research', verbose_name='Исследование'),
        ),
    ]
