# Generated by Django 2.2.5 on 2019-09-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
