# Generated by Django 2.2.5 on 2019-09-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190921_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_cabinet.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.CharField(choices=[('OM', 'На один месяц'), ('OQ', 'На один квартал'), ('HY', 'На пол года'), ('OY', 'На один год')], max_length=2, verbose_name='подписка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Research', verbose_name='Исследование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_frequency',
            field=models.CharField(choices=[('MU', 'Ежемесячное обновление'), ('QU', 'Ежеквартальное обновление')], max_length=2, verbose_name='частота обновления'),
        ),
    ]
