# Generated by Django 2.2.5 on 2019-09-21 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('target', models.TextField()),
                ('description', models.TextField()),
                ('data_update', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('demo', models.FileField(upload_to='')),
                ('contents', models.TextField()),
                ('using_methods', models.TextField()),
                ('data_sources', models.TextField()),
                ('research_type', models.CharField(choices=[('OTR', 'Отраслевое'), ('EXP', 'Экспорт'), ('IMP', 'Импорт')], max_length=3)),
                ('OM_cost', models.BooleanField()),
                ('OQ_cost', models.BooleanField()),
                ('HY_cost', models.BooleanField()),
                ('OY_cost', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Category')),
            ],
            options={
                'verbose_name': ' Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
    ]
