# Generated by Django 2.2.5 on 2019-09-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('target', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_update', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('demo', models.FileField(blank=True, null=True, upload_to='')),
                ('contents', models.TextField(blank=True, null=True)),
                ('using_methods', models.TextField(blank=True, null=True)),
                ('data_sources', models.TextField(blank=True, null=True)),
                ('research_type', models.CharField(choices=[('industry', 'Отраслевое'), ('export', 'Экспорт'), ('import', 'Импорт')], max_length=10)),
                ('OM_cost', models.IntegerField()),
                ('OQ_cost', models.IntegerField(blank=True, null=True)),
                ('HY_cost', models.IntegerField(blank=True, null=True)),
                ('OY_cost', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Category')),
            ],
            options={
                'verbose_name': ' Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
    ]
