# Generated by Django 2.2.5 on 2019-09-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='HY_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='OM_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='OQ_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='OY_cost',
            field=models.FloatField(),
        ),
    ]
