# Generated by Django 2.2.5 on 2019-09-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='research',
            name='HY_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена за полгода'),
        ),
        migrations.AlterField(
            model_name='research',
            name='OM_cost',
            field=models.IntegerField(verbose_name='цена за месяц'),
        ),
        migrations.AlterField(
            model_name='research',
            name='OQ_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена за квартал'),
        ),
        migrations.AlterField(
            model_name='research',
            name='OY_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена за год'),
        ),
        migrations.AlterField(
            model_name='research',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='research',
            name='contents',
            field=models.TextField(blank=True, null=True, verbose_name='Оглавление'),
        ),
        migrations.AlterField(
            model_name='research',
            name='data_sources',
            field=models.TextField(blank=True, null=True, verbose_name='Источники данных'),
        ),
        migrations.AlterField(
            model_name='research',
            name='data_update',
            field=models.TextField(blank=True, null=True, verbose_name='Обновление данных'),
        ),
        migrations.AlterField(
            model_name='research',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Демо файл'),
        ),
        migrations.AlterField(
            model_name='research',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание исследования'),
        ),
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='research',
            name='research_type',
            field=models.CharField(choices=[('industry', 'Отраслевое'), ('export', 'Экспорт'), ('import', 'Импорт')], max_length=10, verbose_name='Тип исследования'),
        ),
        migrations.AlterField(
            model_name='research',
            name='target',
            field=models.TextField(blank=True, null=True, verbose_name='Цель исследования'),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='research',
            name='using_methods',
            field=models.TextField(blank=True, null=True, verbose_name='Используемые методы'),
        ),
    ]
