# Generated by Django 2.2.5 on 2019-10-02 13:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190929_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Оглавление'),
        ),
        migrations.AlterField(
            model_name='research',
            name='data_sources',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Источники данных'),
        ),
        migrations.AlterField(
            model_name='research',
            name='research_type',
            field=ckeditor.fields.RichTextField(choices=[('industry', 'Отраслевое'), ('export', 'Экспорт'), ('import', 'Импорт')], max_length=10, verbose_name='Тип исследования'),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
