# Generated by Django 2.2.5 on 2019-10-02 13:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191002_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='contents',
            field=models.TextField(blank=True, null=True, verbose_name='Оглавление'),
        ),
        migrations.AlterField(
            model_name='research',
            name='using_methods',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Используемые методы'),
        ),
    ]
