# Generated by Django 2.2.5 on 2019-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190921_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='research_type',
            field=models.CharField(choices=[('industry', 'Отраслевое'), ('export', 'Экспорт'), ('import', 'Импорт')], max_length=10),
        ),
    ]
