# Generated by Django 2.2.5 on 2019-10-02 13:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191002_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Оглавление'),
        ),
        migrations.AlterField(
            model_name='research',
            name='research_type',
            field=models.CharField(choices=[('industry', 'Отраслевое'), ('export', 'Экспорт'), ('import', 'Импорт')], max_length=10, verbose_name='Тип исследования'),
        ),
    ]
